### ISSUE TITLE
[Task] Run e2e tests on CI

### ISSUE THREAD

**Issue by tthvo** [COSC-499-W2023/year-long-project-team-1#186]
>
```yaml
name: Cypress Tests

on: push

jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Next.js build cache
              uses: actions/cache@v3
              with:
                  # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
                  path: |
                      ~/.npm
                      ${{ github.workspace }}/.next/cache
                  # Generate a new cache whenever packages or source files change.
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
                  # If source files changed but packages didn't, rebuild from a prior cache.
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            - name: Checkout
              uses: actions/checkout@v4
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  build: npm run build
                  start: npm start
```

> I don't know much about GitHub CI/CD so I left it out of this PR so you could evaluate it :)

> I had to specifically choose to cache Next.js to reduced run time from like 3 minutes to ~1 minute, but like I said I hardly know what I'm doing

_Originally posted by @connordoman in https://github.com/COSC-499-W2023/year-long-project-team-1/issues/179#issuecomment-1827014472_
